### PR TITLE
fix missing jquery and jquery ui references

### LINKED ISSUE #1086: "$ is not defined" when clicking magnifying glass
Click on the magnifying glass to the right of a branch name:
screen shot 2018-05-05 at 3 33 54 pm

An error message is displayed:
screen shot 2018-05-05 at 3 35 53 pm

This appears in the browser console:
```
Uncaught ReferenceError: $ is not defined
    at GitNodeViewModel.showRefSearchForm (git-node.js:166)
    at HTMLButtonElement.<anonymous> (knockout:99)
    at HTMLButtonElement.dispatch (jquery:5183)
    at HTMLButtonElement.elemData.handle (jquery:4991)
    at HTMLButtonElement.d (raven.js:438)
```

No errors displayed in the CLI output.

Can reproduce with:
* Version 1.4.21 installed with npm and
* 671dd02d, started with instructions on CONTRIBUTING page.

Environment:
* node 9.4.0
* npm 6.0.0
* macOS High Sierra

### PR DESCRIPTION
**Pull request by campersau**
fixes #1086

upgrading to `jquery-ui` 1.12 required [some changes to `autocomplete`](https://jqueryui.com/upgrade-guide/1.12/#require-wrappers-for-each-menu-item) and the way to [include the different widgets](https://jqueryui.com/upgrade-guide/1.12/#official-package-on-npm).

### CODE REVIEW

File: components/graph/git-node.js [hunk 1]
```diff
@@ -183,7 +184,6 @@ GitNodeViewModel.prototype.showRefSearchForm = function(obj, event) {
     $(this).autocomplete('search', $(this).val());
   }).data("ui-autocomplete")._renderItem = function (ul, item) {
     return $("<li></li>")
-      .data("item.autocomplete", item)
```
Comment (campersau) [inline components/graph/git-node.js]: This is already taken care of here https://github.com/jquery/jquery-ui/blob/809f29efa79c3c9aba95e6d7ffef41f567cda3a5/ui/widgets/autocomplete.js#L562-L564

**Comment by jung-kim** [comment]
Thanks!

File: public/source/main.js [hunk 2]
```diff
@@ -57,7 +64,11 @@ ko.bindingHandlers.autocomplete = {
           noResults: '',
           results: () => {}
         }
-      });
+      }).data("ui-autocomplete")._renderItem = function (ul, item) {
+        return $("<li></li>")
+          .append($("<a>").text(item.label))
+          .appendTo(ul);
+      };
```
Comment (jung-kim) [inline public/source/main.js]: This is a lovely touch!  👍
